# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:Pincll@2020@tcp(192.168.219.130:3306)/go_learn?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100